var APP_CONSTANTS = {
    BASE_URL: "http://96.45.94.53/",
	//BASE_URL: "http://192.168.20.139:8080/",
    //BASE_URL: "http://192.168.20.55:8080/",
//	BASE_URL: "http://192.168.20.207:8080/",
    API_LOGIN: "login",
    API_LOGOUT: "logout",
    API_DOMAIN: "domain",
    API_RECORDS: "record",
	API_ALL_RECORDS: "records",
    API_USER_CHANGES: "userchanges",
    API_HISTORY: "history",
    API_GEO_FILTER: "geoipfilter",
    API_GEO_PROXIMITY: "geoipproximity",
    API_POOL: "pool",
    API_COMMIT_CHANGES: "save",
    API_UNCOMMITED_CHANGES: "uncommittedchanges",
    API_VANITY: "vanity",
    API_TEMPLATE: "template",
    API_COUNTRIES: "geoipproximity/create",
    API_STATES: "geoipproximity/statesByCountry?countryAbbrv=",
    API_CITIES: "geoipproximity/citiesByState?stateAbbrv=",
    MSG_INVALID_USERNAME_PWD: "The authentication credentials provided were invalid.",
    MSG_TOO_MANY_REQUESTS: "Number of failed login attempts exceeded",
    MSG_EMPTY_USERNAME_PWD: "Please enter username and password.",
	TAG_ID_RECENTLY_UPDATED_DOMAINS : "RecentlyUpdatedDomains",
	TAG_ID_DOMAINS_LIST : "#RecentlyUpdatedDomainsList",
	TAG_ID_UNCOMMITED_DOMAINS : "UncommitedDomains",
    TAG_RECENTLY_UPDATED_DOMAINS_VIEW_ALL: "VIEW ALL DOMAINS",
	TAG_UNCOMMITED_CHANGES_VIEW_ALL: "VIEW ALL",
    MSG_DOMAIN_NAME_REQUIRED: "Domain name is required",
    MSG_DELETE_CONFIRM: "Are you sure you want to delete?",
	MSG_DELETE_RECORDS: "Are you sure you want to delete all records in this domain?",
    MSG_ACTION_FAILED: "Due to an unexpected error, our server is unable to perform the action. Please try again later.",
    MSG_RECORD_NOT_EXIST: "Record not found.",
    DELETE_SUCCESSFUL: 'Deleted successfully',
    DELETE_FAILED:'Delete failed, please try again later',
    MSG_SESSION_TIMEOUT: "Your current session has timed out. Please login again to continue using the app.",
    MSG_FILL_ALL_FIELDS: "Please fill all fields marked with *",
    MSG_COMMIT_CONFIRM: "Are you sure you want to commit?",
    MSG_DELETE_POOL: " will be removed. Do you want to proceed ?",
    MSG_DELETE_VANITY: "Are you sure you want to delete Vanity Nameserver(s)?",
    MSG_DELETE_GEO_PROXIMITY: "Are you sure you want to delete the GeoIP Proximity?",
    MSG_NO_CHANGES: "No changes to save",
    RECORD_STANDARD: "Standard",
    RECORD_FAILOVER: "Failover",
    RECORD_POOLS: "Pools",
    RECORD_ROUNDROBIN: "Roundrobin with Failover",
    TYPE_A: "A",
    TYPE_AAAA: "AAAA",
    TYPE_CNAME: "CNAME",
    TYPE_MX: "MX",
    TYPE_SPF: "SPF",
    TYPE_NS: "NS",
    TYPE_SRV: "SRV",
    TYPE_PTR: "PTR",
    TYPE_TXT: "TXT",
    POOL_A: "ARecordPool",
    POOL_AAAA: "AAAAPool",
    POOL_CNAME: "CNamePool",
    TAG_DOMAIN: "domain",
    TAG_TEMPLATE: "template",
    TAG_VANITY: "Vanity Nameserver",
    TAG_NONE: "none",
    ALERT: "Alert",
    OK: "OK",
    SUCCESS: "Success",
    CANCEL: "Cancel",
    EXIT: "Exit",
    DELETE: "Delete",
	VERSION: "1.0.0",
	SAVE_RECORD: "Added",
	DELETE_RECORD: "Deleted",
	UPDATE_RECORD: "Updated"
}

var JSON_CONSTANTS = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE",
    CONTENT_TYPE: "text/json",
    DATA_TYPE: "json",
    ACCEPT: "text/json",
    STATUS_CODE_404: "404",
    STATUS_CODE_401: "401",
    STATUS_CODE_403: "403",
    STATUS_CODE_302: "302",
}
